# Generated by Django 6.0.5 on 2026-06-04 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='user_auth.rol'),
        ),
    ]
