# Generated by Django 6.0.5 on 2026-06-09 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='document_invalid', message='El documento debe contener entre 6 y 12 números, sin puntos ni espacios.', regex='^\\d{6,12}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='email_invalid', message='La dirección de correo electrónico no es válida', regex="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_names',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='names_invalid', message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='names',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='names_invalid', message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
    ]
