# Generated by Django 6.0.5 on 2026-06-09 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_user_document_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_names',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='names_invalid', message='El nombre solo puede contener letras y espacios.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+(?:[ '-][A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+)*$")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='names',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='names_invalid', message='El nombre solo puede contener letras y espacios.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+(?:[ '-][A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+)*$")]),
        ),
    ]
