# Generated by Django 6.0.5 on 2026-06-16 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_user_document_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='document_invalid', message='El documento debe contener entre 6 y 12 números, sin puntos ni espacios.', regex='\\A\\d{6,12}\\Z')]),
        ),
    ]
