# Generated by Django 6.0.5 on 2026-06-03 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotional_diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotional_diary.diary'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='emotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emotional_diary.emotion'),
        ),
        migrations.AddField(
            model_name='objective',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
