# Generated by Django 6.0.5 on 2026-06-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotional_diary', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
