# Generated by Django 6.0.5 on 2026-06-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotional_diary', '0003_alter_diaryentry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
